// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAS0iVhADqBAb71bl-cYPOhIu2lfYjv9o',
    appId: '1:454865683716:web:0eee3c37ee9ffe35bffc51',
    messagingSenderId: '454865683716',
    projectId: 'ecommerce-fbffb',
    authDomain: 'ecommerce-fbffb.firebaseapp.com',
    databaseURL: 'https://ecommerce-fbffb-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-fbffb.firebasestorage.app',
    measurementId: 'G-GNSC205GH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5LdNHKkNpw84kR1f_7fiad5mteYb9Njk',
    appId: '1:454865683716:android:cedd3d17b9553f3cbffc51',
    messagingSenderId: '454865683716',
    projectId: 'ecommerce-fbffb',
    databaseURL: 'https://ecommerce-fbffb-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-fbffb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm9rDxA_S8z-dpsf2vsCQezNJv1YXZadw',
    appId: '1:454865683716:ios:510b0630e310a270bffc51',
    messagingSenderId: '454865683716',
    projectId: 'ecommerce-fbffb',
    databaseURL: 'https://ecommerce-fbffb-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-fbffb.firebasestorage.app',
    androidClientId:
        '454865683716-ac6irt13e4fp899cujjhce4uvtdhbqmf.apps.googleusercontent.com',
    iosClientId:
        '454865683716-ekqgr97l9hq05niqbhsurorl3dobnbmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm9rDxA_S8z-dpsf2vsCQezNJv1YXZadw',
    appId: '1:454865683716:ios:510b0630e310a270bffc51',
    messagingSenderId: '454865683716',
    projectId: 'ecommerce-fbffb',
    databaseURL: 'https://ecommerce-fbffb-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-fbffb.firebasestorage.app',
    androidClientId:
        '454865683716-ac6irt13e4fp899cujjhce4uvtdhbqmf.apps.googleusercontent.com',
    iosClientId:
        '454865683716-ekqgr97l9hq05niqbhsurorl3dobnbmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAS0iVhADqBAb71bl-cYPOhIu2lfYjv9o',
    appId: '1:454865683716:web:cd31b4c8bc7d2875bffc51',
    messagingSenderId: '454865683716',
    projectId: 'ecommerce-fbffb',
    authDomain: 'ecommerce-fbffb.firebaseapp.com',
    databaseURL: 'https://ecommerce-fbffb-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-fbffb.firebasestorage.app',
    measurementId: 'G-VKVFD01KG5',
  );
}
